# Generated by Django 4.2 on 2024-10-01 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="habits",
            name="is_good",
            field=models.BooleanField(default=True, verbose_name="Полезная привычка"),
        ),
        migrations.AlterField(
            model_name="habits",
            name="periodicity",
            field=models.IntegerField(
                choices=[(1, "Ежедневно"), (7, "Еженедельно"), (30, "Ежемесячно")],
                default=1,
                verbose_name="Периодичность (в днях)",
            ),
        ),
        migrations.AlterField(
            model_name="habits",
            name="time",
            field=models.TimeField(
                help_text="Время, когда надо выполнить привычку", verbose_name="Время"
            ),
        ),
    ]
